CallEventRecord	(0)     CHOICE
(
    moCallRecord	        	(0)	MoCallRecord,
    mtCallRecord                (1)     MtCallRecord,
    roamingRecord               (2)     RoamingRecord,
    incGatewayRecord            (3)     IncGatewayRecord,
    outGatewayRecord            (4)     OutGatewayRecord,
    transitCallRecord           (5)     TransitCallRecord,
    moSMSRecord                 (6)     MOSMSRecord,
    mtSMSRecord                 (7)     MTSMSRecord,
    forwardCallRecord           (100)   MoCallRecord
)
MoCallRecord	        SET
(
    recordType		        	(0)     INTEGER,
    servedIMSI                  (1)     TBCD_STRING,
    servedIMEI                  (2)     TBCD_STRING,
    servedMSISDN                (3)     TBCD_STRING,
    callingNumber               (4)     TBCD_STRING,
    calledNumber                (5)     TBCD_STRING,
    translatedNumber            (6)     TBCD_STRING,
    connectedNumber             (7)     TBCD_STRING,
    roamingNumber               (8)     TBCD_STRING,
    recordingEntity             (9)     TBCD_STRING,
    mscIncomingROUTE            (10)    MscIncomingROUTE,
    mscOutgoingROUTE            (11)    MscOutgoingROUTE,
    location                    (12)    LocationAreaAndCell,
    basicService                (14)    BasicService,
    supplServicesUsed           (17)    SEQUENCE_OF     SuppServiceUsed,
    msClassmark                 (20)    OCTET_STRING,
    answerTime                  (23)    OCTET_STRING,
    releaseTime                 (24)    OCTET_STRING,
    callDuration                (25)    INTEGER,
    causeForTerm                (30)    INTEGER,
    diagnostics                 (31)    Diagnostics,
    callReference               (32)    OCTET_STRING,
    sequenceNumber              (33)    INTEGER,
    additionalChgInfo           (34)    AdditionalChgInfo,
    recordExtensions           	(35)    SET_OF     ManagementExtension,
    serviceKey			(37)    INTEGER,
    networkCallReference        (38)    OCTET_STRING,
    mscAddress                  (39)    TBCD_STRING,
    cAMELCallLegInformation     (54)    SEQUENCE_OF     CAMELInformation,
    systemType                  (61)    INTEGER,
    partialRecordType			(69)    PartialRecordType,	
    chargedParty                (141)   INTEGER,
    orgRNCorBSCId               (167)   OCTET_STRING,
    orgMSCId                    (168)   OCTET_STRING,
    globalAreaID                (188)   CELL_ID,
    subscriberCategory          (190)   OCTET_STRING,
    firstmccmnc                 (192)   OCTET_STRING,
    lastmccmnc                  (194)   OCTET_STRING,
    cUGOutgoingAccessIndicator  (195)   CUGOutgoingAccessIndicator,
    setupTime                   (201)   OCTET_STRING,
    alertingTime                (202)   OCTET_STRING,
    voiceIndicator              (203)   VoiceIndicator,
    networkOperatorId           (223)   OCTET_STRING,
    recordNumber                (232)   INTEGER,
    chargeLevel                 (237)   ChargeLevel,
    mscOutgoingROUTENumber      (261)   INTEGER,
    mscIncomingROUTENumber      (262)   INTEGER,
    globalCallReference         (290)   OCTET_STRING,
    callerIPInformation         (291)   IPInformationEvent,
    causeLocation               (295)   CauseLocation,
    ringingDuration             (307)   INTEGER
)
MtCallRecord            SET
(
    recordType		        	(0)     INTEGER,
    servedIMSI                  (1)     TBCD_STRING,
    servedIMEI                  (2)     TBCD_STRING,
    servedMSISDN                (3)     TBCD_STRING,
    callingNumber               (4)     TBCD_STRING,
    connectedNumber             (5)     TBCD_STRING,
    roamingNumber               (160)   TBCD_STRING,
    recordingEntity             (6)     TBCD_STRING,
    mscIncomingROUTE            (7)     MscIncomingROUTE,
    mscOutgoingROUTE            (8)     MscOutgoingROUTE,
    location                    (9)     LocationAreaAndCell,
    basicService                (11)    BasicService,
    supplServicesUsed           (14)    SEQUENCE_OF     SuppServiceUsed,
    msClassmark                 (17)    OCTET_STRING,
    answerTime                  (20)    OCTET_STRING,
    releaseTime                 (21)    OCTET_STRING,
    callDuration                (22)    INTEGER,
    causeForTerm                (27)    INTEGER,
    diagnostics                 (28)    Diagnostics,
    callReference               (29)    OCTET_STRING,
    sequenceNumber              (30)    INTEGER,
    additionalChgInfo           (31)    AdditionalChgInfo,
    recordExtensions           	(32)    SET_OF ManagementExtension,
    networkCallReference        (33)    OCTET_STRING,
    mscAddress                  (34)    TBCD_STRING,
    serviceKey			(45)    INTEGER,
    systemType                  (46)    INTEGER,
    partialRecordType			(54)    PartialRecordType,
    chargedParty                (141)   INTEGER,
    originalCalledNumber        (142)   TBCD_STRING,
    orgRNCorBSCId               (167)   OCTET_STRING,
    orgMSCId                    (168)   OCTET_STRING,
    globalAreaID                (188)   CELL_ID,
    subscriberCategory          (190)   OCTET_STRING,
    firstmccmnc                 (192)   OCTET_STRING,
    lastmccmnc                  (194)   OCTET_STRING,
    cUGOutgoingAccessIndicator  (195)   CUGOutgoingAccessIndicator,
    redirectingnumber           (203)   TBCD_STRING,
    setupTime                   (204)   OCTET_STRING,
    alertingTime                (202)   OCTET_STRING,
    calledNumber                (205)   TBCD_STRING,
    voiceIndicator              (206)   VoiceIndicator,
    networkOperatorId           (223)   OCTET_STRING,
    recordNumber                (232)   INTEGER,
    chargeLevel                 (237)   ChargeLevel,
    translatedNumber            (245)   TBCD_STRING,
    mscOutgoingROUTENumber      (261)   MscOutgoingROUTENumber,
    mscIncomingROUTENumber      (262)   MscIncomingROUTENumber,
    globalCallReference         (290)   OCTET_STRING,
    calledIPInformation         (292)   IPInformationEvent,
    causeLocation               (295)   CauseLocation,
    ringingDuration             (307)   INTEGER
)
RoamingRecord           SET
(
    recordType		        	(0)     INTEGER,
    servedIMSI                  (1)     TBCD_STRING,
    servedMSISDN                (2)     TBCD_STRING,
    callingNumber               (3)     TBCD_STRING,
    roamingNumber               (4)     TBCD_STRING,
    recordingEntity             (5)     TBCD_STRING,
    mscIncomingROUTE            (6)     MscIncomingROUTE,
    mscOutgoingROUTE            (7)     MscOutgoingROUTE,
    basicService                (8)     BasicService,
    answerTime                  (13)    OCTET_STRING,
    releaseTime                 (14)    OCTET_STRING,
    callDuration                (15)    INTEGER,
    causeForTerm                (17)    INTEGER,
    diagnostics                 (18)    Diagnostics,
    callReference               (19)    OCTET_STRING,
    recordExtensions           	(21)    SET_OF ManagementExtension,
    partialRecordType			(30)    PartialRecordType,
    additionalChgInfo           (133)   AdditionalChgInfo,
    networkCallReference        (22)    OCTET_STRING,
    mscAddress                  (23)    TBCD_STRING,
    chargedParty                (141)   INTEGER,
    orgMSCId                    (168)   OCTET_STRING,
    subscriberCategory          (190)   OCTET_STRING,
    cUGOutgoingAccessIndicator  (195)   CUGOutgoingAccessIndicator,
    serviceKey                  (217)   INTEGER,
    recordNumber                (232)   INTEGER,
    translatedNumber            (245)   TBCD_STRING,
    mscOutgoingROUTENumber      (261)   MscOutgoingROUTENumber,
    mscIncomingROUTENumber      (262)   MscIncomingROUTENumber,
    globalCallReference         (290)   OCTET_STRING
)
TransitCallRecord       SET
(
    recordType		        	(0)     INTEGER,
    callingNumber               (4)     TBCD_STRING,
    calledNumber                (5)     TBCD_STRING,
    recordingEntity             (1)     TBCD_STRING,
    mscIncomingROUTE            (2)     MscIncomingROUTE,
    mscOutgoingROUTE            (3)     MscOutgoingROUTE,
    basicService                (130)   BasicService,
    answerTime                  (8)     OCTET_STRING,
    releaseTime                 (9)     OCTET_STRING,
    callDuration                (10)    INTEGER,
    causeForTerm                (12)    INTEGER,
    diagnostics                 (13)    Diagnostics,
    callReference               (14)    OCTET_STRING,
    sequenceNumber              (15)    INTEGER,
    recordExtensions           	(16)    SET_OF     ManagementExtension,
    partialRecordType			(23)    PartialRecordType,
    additionalChgInfo           (133)   AdditionalChgInfo,
    cUGOutgoingAccessIndicator  (195)   CUGOutgoingAccessIndicator,
	mscIncomingRouteAttribute   (198)   RouteAttribute,
	mscOutgoingRouteAttribute   (199)   RouteAttribute,
    networkCallReference        (200)   OCTET_STRING,
    setupTime                   (201)   OCTET_STRING,
    alertingTime                (202)   OCTET_STRING,
    voiceIndicator              (203)   VoiceIndicator,
    orgMSCId                    (168)   OCTET_STRING,
    networkOperatorId           (223)   OCTET_STRING,
	recordNumber                (232)   INTEGER,
    chargeLevel                 (237)   ChargeLevel,
    translatedNumber            (245)   TBCD_STRING,
    mscOutgoingROUTENumber      (261)   MscOutgoingROUTENumber,
    mscIncomingROUTENumber      (262)   MscIncomingROUTENumber,
    globalCallReference         (290)   OCTET_STRING,
    callerIPInformation         (291)   IPInformationEvent,
    calledIPInformation         (292)   IPInformationEvent,
    causeLocation               (295)   CauseLocation
)
IncGatewayRecord        SET
(
    recordType		        	(0)     INTEGER,
    callingNumber               (1)     TBCD_STRING,
    calledNumber                (2)     TBCD_STRING,
    roamingNumber               (160)   TBCD_STRING,
    recordingEntity             (3)     TBCD_STRING,
    mscIncomingROUTE            (4)     MscIncomingROUTE,
    mscOutgoingROUTE            (5)     MscOutgoingROUTE,
    basicService                (130)   BasicService,
    answerTime                  (7)     OCTET_STRING,
    releaseTime                 (8)     OCTET_STRING,
    callDuration                (9)     INTEGER,
    causeForTerm                (11)    INTEGER,
    diagnostics                 (12)    Diagnostics,
    callReference               (13)    OCTET_STRING,
    sequenceNumber              (14)    INTEGER,
    recordExtensions           	(15)    SET_OF ManagementExtension,
    partialRecordType			(22)    PartialRecordType,
    additionalChgInfo           (133)   AdditionalChgInfo,
    cUGOutgoingAccessIndicator  (195)   CUGOutgoingAccessIndicator,
	mscIncomingRouteAttribute   (198)   RouteAttribute,
	mscOutgoingRouteAttribute   (199)   RouteAttribute,
    networkCallReference        (200)   OCTET_STRING,
    setupTime                   (201)   OCTET_STRING,
    alertingTime                (202)   OCTET_STRING,
    orgMSCId                    (168)   OCTET_STRING,
    voiceIndicator              (203)   VoiceIndicator,
    networkOperatorId           (223)   OCTET_STRING,
	recordNumber                (232)   INTEGER,
    chargeLevel                 (237)   ChargeLevel,
    translatedNumber            (245)   TBCD_STRING,
    location                    (247)   LocationAreaAndCell,
    mscOutgoingROUTENumber      (261)   MscOutgoingROUTENumber,
    mscIncomingROUTENumber      (262)   MscIncomingROUTENumber,
    globalCallReference         (290)   OCTET_STRING,
    callerIPInformation         (291)   IPInformationEvent,
    calledIPInformation         (292)   IPInformationEvent,
    causeLocation               (295)   CauseLocation
)
OutGatewayRecord        SET
(
    recordType		        	(0)     INTEGER,
    callingNumber               (1)     TBCD_STRING,
    calledNumber                (2)     TBCD_STRING,
    roamingNumber               (160)   TBCD_STRING,
    recordingEntity             (3)     TBCD_STRING,
    mscIncomingROUTE            (4)     MscIncomingROUTE,
    mscOutgoingROUTE            (5)     MscOutgoingROUTE,
    answerTime                  (7)     OCTET_STRING,
    releaseTime                 (8)     OCTET_STRING,
    callDuration                (9)     INTEGER,
    causeForTerm                (11)    INTEGER,
    diagnostics                 (12)    Diagnostics,
    callReference               (13)    OCTET_STRING,
    recordExtensions           	(15)    SET_OF ManagementExtension,
    partialRecordType			(22)    PartialRecordType,
    basicService                (130)   BasicService,
    additionalChgInfo           (133)   AdditionalChgInfo,
    networkCallReference        (200)   OCTET_STRING,
    orgMSCId                    (168)   OCTET_STRING,
    cUGOutgoingAccessIndicator  (195)   CUGOutgoingAccessIndicator,
	mscIncomingRouteAttribute   (198)   RouteAttribute,
	mscOutgoingRouteAttribute   (199)   RouteAttribute,
    setupTime                   (201)   OCTET_STRING,
    alertingTime                (202)   OCTET_STRING,
    voiceIndicator              (203)   VoiceIndicator,
    networkOperatorId           (223)   OCTET_STRING,
	recordNumber                (232)   INTEGER,
    chargeLevel                 (237)   ChargeLevel,
    firstmccmnc                 (249)   OCTET_STRING,
    lastmccmnc                  (250)   OCTET_STRING,
    translatedNumber            (245)   TBCD_STRING,
    location                    (247)   LocationAreaAndCell,
    mscOutgoingROUTENumber      (261)   MscOutgoingROUTENumber,
    mscIncomingROUTENumber      (262)   MscIncomingROUTENumber,
    globalCallReference         (290)   OCTET_STRING,
    callerIPInformation         (291)   IPInformationEvent,
    calledIPInformation         (292)   IPInformationEvent,
    causeLocation               (295)   CauseLocation
)
ForwardCallRecord   SET
(
    recordType		        	(0)     INTEGER,
    servedIMSI                  (1)     TBCD_STRING,
    servedIMEI                  (2)     TBCD_STRING,
    servedMSISDN                (3)     TBCD_STRING,
    callingNumber               (4)     TBCD_STRING,
    calledNumber                (5)     TBCD_STRING,
    translatedNumber            (6)     TBCD_STRING,
    roamingNumber               (8)     TBCD_STRING,
    recordingEntity             (9)     TBCD_STRING,
    mscIncomingROUTE            (10)    MscIncomingROUTE,
    mscOutgoingROUTE            (11)    MscOutgoingROUTE,
    location                    (12)    LocationAreaAndCell,
    basicService                (14)    BasicService,
    msClassmark                 (20)    OCTET_STRING,
    answerTime                  (23)    OCTET_STRING,
    releaseTime                 (24)    OCTET_STRING,
    callDuration                (25)    INTEGER,
    causeForTerm                (30)    INTEGER,
    diagnostics                 (31)    Diagnostics,
    callReference               (32)    OCTET_STRING,
    sequenceNumber              (33)    INTEGER,
    additionalChgInfo           (34)    AdditionalChgInfo,
    networkCallReference        (38)    OCTET_STRING,
    mscAddress                  (39)    TBCD_STRING,
    systemType                  (61)    INTEGER,
    chargedParty                (141)   INTEGER,
    orgRNCorBSCId               (167)   OCTET_STRING,
    orgMSCId                    (168)   OCTET_STRING,
    globalAreaID                (188)   CELL_ID,
    subscriberCategory          (190)   OCTET_STRING,
    firstmccmnc                 (192)   OCTET_STRING,
    lastmccmnc                  (194)   OCTET_STRING,
	recordNumber                (232)   INTEGER,
    mscOutgoingROUTENumber      (261)   INTEGER,
    mscIncomingROUTENumber      (262)   INTEGER,
    globalCallReference         (290)   OCTET_STRING
)
MOSMSRecord             SET
(
    recordType		        	(0)     INTEGER,
    servedIMSI                  (1)     TBCD_STRING,
    servedIMEI                  (2)     TBCD_STRING,
    servedMSISDN                (3)     TBCD_STRING,
    msClassmark                 (4)     OCTET_STRING,
    serviceCentre               (5)     TBCD_STRING,
    recordingEntity             (6)     TBCD_STRING,
    location                    (7)     LocationAreaAndCell,
    messageReference            (8)     OCTET_STRING,
    originationTime             (9)     OCTET_STRING,
    recordExtensions           	(11)    SET_OF ManagementExtension,
    destinationNumber           (12)    TBCD_STRING,
    systemType                  (14)    INTEGER,
    basicService                (130)   BasicService,
    additionalChgInfo           (133)   AdditionalChgInfo,
    chargedParty                (141)   INTEGER,
    orgRNCorBSCId               (167)   OCTET_STRING,
    orgMSCId                    (168)   OCTET_STRING,
    globalAreaID                (188)   CELL_ID,
    subscriberCategory          (190)   OCTET_STRING,
    firstmccmnc                 (192)   OCTET_STRING,
    smsUserDataType             (195)   OCTET_STRING,
    smsText                     (196)    OCTET_STRING,
    callReference               (201)    OCTET_STRING,
    networkOperatorId           (223)   OCTET_STRING,
	recordNumber                (232)   INTEGER,
    chargeLevel                 (237)   ChargeLevel
)
MTSMSRecord              SET
(
    recordType		        	(0)     INTEGER,
    serviceCentre               (1)     TBCD_STRING,
    servedIMSI                  (2)     TBCD_STRING,
    servedIMEI                  (3)     TBCD_STRING,
    servedMSISDN                (4)     TBCD_STRING,
    msClassmark                 (5)     OCTET_STRING,
    recordingEntity             (6)     TBCD_STRING,
    location                    (7)     LocationAreaAndCell,
    deliveryTime                (8)     OCTET_STRING,
    recordExtensions           	(10)    SET_OF ManagementExtension,
    systemType                  (11)    INTEGER,
    basicService                (130)   BasicService,
    additionalChgInfo           (133)   AdditionalChgInfo,
    chargedParty                (141)   INTEGER,
    orgRNCorBSCId               (167)   OCTET_STRING,
    orgMSCId                    (168)   OCTET_STRING,
    globalAreaID                (188)   CELL_ID,
    subscriberCategory          (190)   OCTET_STRING,
    firstmccmnc                 (192)   OCTET_STRING,
    smsUserDataType             (195)   OCTET_STRING,
    smsText                     (196)   OCTET_STRING,
    origination                 (201)   TBCD_STRING,
    callReference               (202)   OCTET_STRING,
    networkOperatorId           (223)   OCTET_STRING,
	recordNumber                (232)   INTEGER,
    chargeLevel                 (237)   ChargeLevel
)
MscIncomingROUTE        SET
(
    mscIncoming                 (1)     IA5STRING
)
MscOutgoingROUTE        SET
(
    mscOutgoing                 (1)     IA5String
)
Location    SET
(
    loca                        (0)     OCTET_STRING,
    changeOfLocation            (1)     OCTET_STRING
)
LocationAreaAndCell    SET
(
    locationAreaCode            (0)     OCTET_STRING
)
BasicService            SET
(
    bsService                   (3)     OCTET_STRING
)
Diagnostics CHOICE
(
    gsm0408Cause                   (0)     INTEGER,
    gsm0902MapErrorValue                   (1)     INTEGER,
    ccittQ767Cause                   (2)     INTEGER,
    networkSpecificCause                   (3)     SET_OF	ManagementExtension,
    manufacturerSpecificCause                   (4)     SET_OF	ManagementExtension
)

AdditionalChgInfo       SET
(
   AddChargeInfo                (0)     INTEGER
)
CAMELInformation        SET
(
   cAMELDestinationNumber       (1)     TBCD_STRING
)
SuppServiceUsed         SEQUENCE
(
    ssCode                      (0)     OCTET_STRING,
    ssTime                      (1)     OCTET_STRING,
    relatedNumber               (2)     TBCD_STRING
)

ManagementExtension             SEQUENCE
(
    identifier                      (0)     TBCD_STRING,
    significance                      (1)     INTEGER,	
    information                      (2)     OCTET_STRING
)

PartialRecordType             ENUMERATED
(
    timeLimit                       0,
    serviceChange                   1,
    locationChange                  2,
    classmarkChange                 3,
    aocParmChange                   4,
    radioChannelChange              5,
    hSCSDParmChange                 6,
    changeOfCAMELDestination        7,
    camelCPHOperationsOnCallLegs    8,
    secondAnswer                    9,
    firstHotBill                   20,
    severalSSOperationBill         21,
    iSTalertTimeOut                22,
    bearRedirectStart              23,
    bearRedirectStop               24,
    triggerDCHcontinue             25,
    iNAPCS1Shortnumber             26,
    roLinkFail                     27,
    lclsactive                     28,
    lclsdeactive                   29,
    suspendResumeIndicator         30
)

CUGOutgoingAccessIndicator    ENUMERATED
(
    notCUGCall  0,
    cUGCall     1	
)

RouteAttribute    ENUMERATED
(
    cas    0,
    tup    1,
    isup   2,
    pra    3,
    bicc   4,
    sip    5,
    others 255
)

VoiceIndicator    ENUMERATED
(
    sendToneByLocalMsc 0,
    sendToneByOtherMsc 1,
    voiceNoIndication  3
)

ChargeLevel    ENUMERATED
(
    chargeBySecond      0,
    chargeBy10ms        1,
    chargeBy100ms       2
)

IPInformationEvent SEQUENCE
(
    originatingIPAddress  (0) OCTET_STRING,
    terminatingIPAddress  (1) OCTET_STRING,
    passertedIdentity     (2) TBCD_STRING,
    usedCodecList         (3) OCTET_STRING,
    originatingPort       (4) INTEGER,
    terminatingPort       (5) INTEGER,
    qosStatistics         (6) TBCD_STRING
)

CauseLocation    ENUMERATED
(
    user                        0,
    localprivatenetwork       1,
    localnetwork               2,
    transitnetwork             3,
    remotelocalnetwork        4,
    remoteprivatenetwork      5,
    internationalnetwork       7,
    beyondaninterworkingpoint   10,
    unknown                        11
)